import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import {MdAddCircleOutline} from 'react-icons/md'
import emt from "../public/empty.jpeg";
import Results from "../components/Results";

import Footer from "../components/Footer";
import Collectres from "../components/Collectres";
import Link from "next/link";
export default function Collections({ coll }) {
  // console.log(coll.length);
  return (
    <>
      <Head>
        <title>Hulu-2 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {coll.length === 0 && (
        <div className="flex">
          <div className="w-3/5 p-10">

          <Image
            className="object-fill align-middle flex  "
            alt="image"
            layout="responsive"
            src="https://i.pinimg.com/originals/10/41/5d/10415d2d0accbbd6ae2ce6018fea86b9.jpg"
            width={100}
            height={80}
          />
          </div>
          <div className="w-2/5 p-5 mt-40 ">
            
              <h1 className="title-font sm:text-6xl text-3xl tracking-wide mb-2  font-medium text-white">
                {" "}
                Watchlist is Empty
                <br />
                <br/>
                 Add Now
              </h1>
              <Link href={"/movies"}>

              <h1 className="title-font transition delay-150 duration-300 ease-in-out inline-block hover:shadow-2xl hover:shadow-neutral-700  hover:text-[#ff0000]  hover:cursor-pointer hover:scale-125 pl-56 sm:text-4xl text-2xl  mb-4 font-light text-green-500">
                <MdAddCircleOutline/>
              </h1>
              </Link>
              <br />
            </div>
          
        </div>
      )}

      <Collectres results={coll} />
      {/* <Results results={mydata} /> */}
      <Footer />
    </>
  );
}

export async function getServerSideProps() {
  let req = await fetch("http://localhost:9000/posts");

  let data = await req?.json();
  // console.log(data);
  return {
    props: { coll: data }, // will be passed to the page component as props
  };
}
