
// function searchresults() {
//   return (
//     <div>searchresults</div>
//   )
// }

// export default searchresults


import Head from "next/head";
import Image from "next/image";
import Details from "./Details";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import requests from "../utils/requests";
import Footer from "../components/Footer";

export default function searchresults({mydata}) {
  console.log(mydata);
  return (
    <>

      <Head>
        <title>Hulu-2 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Results results={mydata} />
      <Footer/>
    </>
  );
}


export async function getServerSideProps(context) {
  const sea=context.query.name
  // console.log(`https://api.themoviedb.org/3${requests[genre]?.url}`);
  let req= await fetch(`https://api.themoviedb.org/3/search/movie?api_key=49104ed84bd4fa58190e3ad74f40d7d4&language=en-US&query=${sea}&page=1&include_adult=false `)
  let mydata=await req?.json();
  console.log(sea);
  return {
    props: {mydata}, // will be passed to the page component as props
  }
}